#! /bin/sh

set -e

cd "$(dirname "$0")"

echo "Installing LoRa Flow..."
sudo cp loraflow.py /usr/local/bin/
sudo chmod +x /usr/local/bin/loraflow.py

echo "Adding to startup..."
sudo cp loraflow.sh /etc/init.d/
sudo chmod +x /etc/init.d/loraflow.sh

sudo update-rc.d loraflow.sh defaults
sudo /etc/init.d/loraflow.sh start

echo "LoRa Flow has been installed!"
echo "+---------------------------------------------------------+"
echo "| Please configure Maria DB (MySQL) credentials: sudo nano -w loraflow/loraflow.py"
echo "+---------------------------------------------------------+"
echo "START COMMAND: /etc/init.d/loraflow.sh start"
echo "STOP COMMAND: /etc/init.d/loraflow.sh stop\n"
